# Generated by Django 5.1.2 on 2024-12-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.CharField(max_length=255)),
                ('user2_id', models.CharField(max_length=255)),
                ('score1', models.CharField(max_length=255)),
                ('score2', models.CharField(max_length=255)),
            ],
        ),
    ]
